imports:
- path: /mnt/c/Users/mihenandi-fuki.wony/Documents/ysance/52entertainment/infra_as_code/resources/pubsub/pubsub.jinja
- path: /mnt/c/Users/mihenandi-fuki.wony/Documents/ysance/52entertainment/infra_as_code/resources/bigquery/bigquery.jinja
- path: /mnt/c/Users/mihenandi-fuki.wony/Documents/ysance/52entertainment/infra_as_code/resources/dataflow/dataflow.jinja
- path: /mnt/c/Users/mihenandi-fuki.wony/Documents/ysance/52entertainment/infra_as_code/resources/storage/storage.jinja


# In the resources section below, the properties of the resources are replaced
# with the names of the templates.
resources:
- name: pubsub
  type: /mnt/c/Users/mihenandi-fuki.wony/Documents/ysance/52entertainment/infra_as_code/pubsub/pubsub.jinja
  properties:
    ackDeadlineSeconds: 30

- name: bigquery
  type: /mnt/c/Users/mihenandi-fuki.wony/Documents/ysance/52entertainment/infra_as_code/bigquery/bigquery.jinja

- name: storage
  type: storage.jinja
  properties:
    name: test-bucket-name
    region: us-central1
    storageClass: REGIONAL

- name: "my-topic-to-avro"
  type: 'ysance-billing/dataflow:dataflow.projects.locations.templates.launch'
  properties:
    projectId: ysance-billing
    gcsPath: "gs://test-create-123"
    jobName: "my-topic-to-avro"
    location: "europe-west1"
    parameters:
      inputTopic: "projects/ysance-billing/topics/test"
      outputDirectory: "gs://test-create-123/"
      avroTempDirectory: "gs://test-create-123/"

- name: dataflow
  type: ysance-billing/dataflow:dataflow.projects.locations.templates.launch
  properties:
    projectId: ysance-billing
    location: us-central1
    gcsPath: gs://dataflow-templates-us-central1/latest/Word_Count
    jobName: testing-job2
    environment:
      bypassTempDirValidation: false
      tempLocation: gs://test-create-123/dataflow/tmp
      ipConfiguration: WORKER_IP_UNSPECIFIED
      additionalExperiments: []
    parameters:
      inputFile: gs://dataflow-samples-test123/shakespeare/kinglear.txt
      output: gs://test-create-123/dataflow/output/myoutput


