imports:
- path: resources/pubsub/pubsub.jinja
- path: resources/bigquery/bigquery.jinja
- path: resources/storage/storage.jinja
- path: resources/cloudbuild/cloudbuild.jinja
- path: infra_as_code/app.jinja


# In the resources section below, the properties of the resources are replaced
# with the names of the templates.
resources:
- name: app-template
  type: app.jinja
